global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'python-services'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'api:8000'
          - 'data:9001'
          - 'engine:9010'
          - 'transformer:8089'

  - job_name: 'nginx'
    metrics_path: /metrics
    static_configs:
      - targets: ['nginx:9113']  # requires nginx exporter sidecar or module (future)

  - job_name: 'ollama'
    metrics_path: /metrics
    static_configs:
      - targets: ['ollama:11434']  # placeholder if metrics exposed in future

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.yml

# Future exporters (node_exporter, cadvisor) can be added here.
