# Additional custom queries can be placed here.
# Example (commented):
# pg_replication:
#   query: |
#     SELECT pid, state, sync_state, sent_lsn, write_lsn, flush_lsn, replay_lsn
#     FROM pg_stat_replication;
#   metrics:
#     - pid:
#         usage: "LABEL"
#         description: "Process ID"
